Cards = [
  "Truth be told, my favorite food-related mascot is ___.",
  "Truth be told, a great commercial is ___.",
  "Truth be told, I once made a ___.",
  "Truth be told, I've sworn off ___.",
  "Truth be told, I should clean up my ___.",
  "Truth be told, I once had my picture taken with ___.",
  "Truth be told, the last thing I fixed was ___.",
  "Truth be told, I keep meaning to ___.",
  "Truth be told, my first word should have been ___.",
  "Truth be told, I think I'm good at ___.",
  "Truth be told, I can't wait until computers can ___.",
  "Truth be told, the largest object that made me happy was ___.",
  "Truth be told, I always make sure I have enough ___.",
  "Truth be told, I often worry about ___.",
  "Truth be told, the weirdest thing I searched for on the internet was ___.",
  "Truth be told, I ___.",
  "Truth be told, I never forgot ___.",
  "Truth be told, I still have my ___.",
  "Truth be told, I have a pet name for ___.",
  "Truth be told, it's a little known fact that I ___.",
  "Truth be told, after a long day I really look forward to ___.",
  "Truth be told, I looooove to play ___.",
  "Truth be told, a game I was once addicted to playing was ___.",
  "Truth be told, the thing I own that I wish I didn't is ___.",
  "Truth be told, the next place I want to go is ___.",
  "Truth be told, I think a great thing about getting older is ___.",
  "Truth be told, the last time I broke a sweat, I was ___.",
  "Truth be told, I long for ___.",
  "Truth be told, I'm obsessive about ___.",
  "Truth be told, the animal or insect that terrifies me most is ___.",
  "Truth be told, one of my biggest accomplishments is ___.",
  "Truth be told, a big influence on me was ___.",
  "Truth be told, I am not a fan of ___.",
  "Truth be told, I believe that one day ___.",
  "Truth be told, I feel guilty after ___.",
  "Truth be told, I really can't stand ___.",
  "Truth be told, I am not built for ___.",
  "Truth be told, I have a hard time making a decision when it comes to ___.",
  "Truth be told, I know someone who lives in ___.",
  "Truth be told, I've changed my opinion on ___.",
  "Truth be told, I've never been ___.",
  "Truth be told, I have a long ___.",
  "Truth be told, I once got stuck in ___.",
  "Truth be told, the last gift I purchased was ___.",
  "Truth be told, I'm not shy about ___.",
  "Truth be told, my next tattoo would be ___.",
  "Truth be told, I'm embarrassed to admit it, but I love ___.",
  "Truth be told, one of my favorite childhood memories is ___.",
  "Truth be told, I wish I were still ___.",
  "Truth be told, there's really nothing like ___.",
  "Truth be told, I have most recently been complaining about ___.",
  "Truth be told, a memorable moment from high school was ___.",
  "Truth be told, it took me forever to finally ___.",
  "Truth be told, I don't like to share ___.",
  "Truth be told, I'm very particular about the look of my ___.",
  "Truth be told, I do not find it amusing when ___.",
  "Truth be told, my specialty in the kitchen is ___.",
  "Truth be told, a website I always go to is ___.",
  "Truth be told, I can't say \"no\" to ___.",
  "Truth be told, in the future I hope ___.",
  "Truth be told, a great line from a movie is ___.",
  "Truth be told, when someone says \"inner tube\" I think of ___.",
  "Truth be told, my neighbor has a ___.",
  "Truth be told, I must confess ___.",
  "Truth be told, I still wish I could ___.",
  "Truth be told, a movie that never gets old is ___.",
  "Truth be told, my favorite way to eat a potato is ___.",
  "Truth be told, I actually know the phone number for ___.",
  "Truth be told, the last thing I cooked was ___.",
  "Truth be told, my favorite take-out food is ___.",
  "Truth be told, I would go back to school for ___.",
  "Truth be told, I once gave someone a ___.",
  "Truth be told, it's been at least two years since I ___.",
  "Truth be told, the last thing I comparison shopped for was ___.",
  "Truth be told, it would be difficult for me to give up ___.",
  "Truth be told, I own at least five ___.",
  "Truth be told, something I hate to touch is ___.",
  "Truth be told, I have fantasized about ___.",
  "Truth be told, the last movie I watched was ___.",
  "Truth be told, the first trip or vacation I remember taking is ___.",
  "Truth be told, an odd contact in my cell phone is ___.",
  "Truth be told, the person I think would be a good president is ___.",
  "Truth be told, the dirtiest spot in my house is ___.",
  "Truth be told, I would never want to be a ___.",
  "Truth be told, when I'm at the movies I cannot stand it when ___.",
  "Truth be told, I'm uncomfortable sharing my ___.",
  "Truth be told, I once won ___.",
  "Truth be told, I can't get enough ___.",
  "Truth be told, I bet you didn't know that I ___.",
  "Truth be told, a great form of exercise is ___.",
  "Truth be told, I cannot ___.",
  "Truth be told, I was really surprised when ___.",
  "Truth be told, I have always had a soft spot for ___.",
  "Truth be told, people think it's funny when I ___.",
  "Truth be told, I was the first in my family to ___.",
  "Truth be told, I hope I never lose my ___.",
  "Truth be told, a vivid memory of elementary school is ___.",
  "Truth be told, I'd say I got a real bargain on ___.",
  "Truth be told, I should have never ___.",
  "Truth be told, I could give a good speech on ___.",
  "Truth be told, I once had the nickname ___.",
  "Truth be told, a food I could eat every day is ___.",
  "Truth be told, one time I forgot ___.",
  "Truth be told, it's not fair that ___.",
  "Truth be told, I wish I were better at ___.",
  "Truth be told, I wish they would bring back ___.",
  "Truth be told, I still smile when I think of ___.",
  "Truth be told, I would watch anything with ___.",
  "Truth be told, in 10 years I can see myself ___.",
  "Truth be told, I'm tired of hearing about ___.",
  "Truth be told, one time I grew ___.",
  "Truth be told, if I only owned one piece of furniture it would be ___.",
  "Truth be told, when I need advice I go to ___.",
  "Truth be told, one time in school I ___.",
  "Truth be told, in my family, I am considered the ___.",
  "Truth be told, out of everyone here, I would be least likely to ___.",
  "Truth be told, I always cry when ___.",
  "Truth be told, out of everyone here, I am probably the worst ___.",
  "Truth be told, I was a member of ___.",
  "Truth be told, the body part I like the most is ___.",
  "Truth be told, one thing I dread doing is ___.",
  "Truth be told, I'm really looking forward to ___.",
  "Truth be told, the thing I like the most about myself is ___.",
  "Truth be told, I used to have a poster of ___.",
  "Truth be told, I used to ___.",
  "Truth be told, I have a gigantic ___.",
  "Truth be told, my most prized possession is ___.",
  "Truth be told, I can't believe I used to play with ___.",
  "Truth be told, I wish I had a nickel for every time I ___.",
  "Truth be told, on a typical Saturday, you'll find me ___.",
  "Truth be told, I'm inspired by ___.",
  "Truth be told, it's never too late to ___.",
  "Truth be told, I like to watch ___.",
  "Truth be told, after school I would often ___.",
  "Truth be told, my mom once told me ___.",
  "Truth be told, I always giggle at ___.",
  "Truth be told, on weekends I like to ___.",
  "Truth be told, a product that completely baffles me is ___.",
  "Truth be told, I keep losing my ___.",
  "Truth be told, I would never be caught dead wearing ___.",
  "Truth be told, I have two ___.",
  "Truth be told, I think moustaches are ___.",
  "Truth be told, I can't wait to ___.",
  "Truth be told, I never want anyone to see my ___.",
  "Truth be told, I would never want to work as a ___.",
  "Truth be told, my mom used to always make ___.",
  "Truth be told, a crazy thing I did was ___.",
  "Truth be told, I will never finish ___.",
  "Truth be told, the biggest thing I've ever seen is ___.",
  "Truth be told, I dream about ___.",
  "Truth be told, the worst part of going to the dentist is ___.",
  "Truth be told, people often compliment me on ___.",
  "Truth be told, I love to wear ___.",
  "Truth be told, I get butterflies in my stomach before ___.",
  "Truth be told, one time in gym class I ___.",
  "Truth be told, if I could add a single option to my car, it would be ___.",
  "Truth be told, a teacher once told me ___.",
  "Truth be told, I wish somebody would have told me ___.",
  "Truth be told, I would play hooky to go ___.",
  "Truth be told, the best thing about Sweden is ___.",
  "Truth be told, it took me a long time to accept ___.",
  "Truth be told, it's been a long time since I ___.",
  "Truth be told, one thing I keep in my nightstand is ___.",
  "Truth be told, my morning routine includes ___.",
  "Truth be told, the best part of summer is ___.",
  "Truth be told, a TV or radio commercial that I'm really sick of is ___.",
  "Truth be told, I feel like I'm always buying ___.",
  "Truth be told, a candy that I've never cared for is ___.",
  "Truth be told, I'm always late for ___.",
  "Truth be told, someone once stole my ___.",
  "Truth be told, don't touch my ___.",
  "Truth be told, I can't help but be nosy about ___.",
  "Truth be told, I cut corners when it comes to ___.",
  "Truth be told, I had a subscription to ___.",
  "Truth be told, the first thing I do when I get home from work is ___.",
  "Truth be told, I'm a slow ___.",
  "Truth be told, I have the autograph of ___.",
  "Truth be told, people say I am usually pretty ___.",
  "Truth be told, when I am alone I ___.",
  "Truth be told, I often read ___.",
  "Truth be told, in my drawer I keep ___.",
  "Truth be told, I have a bone to pick with ___.",
  "Truth be told, I hope I never have to ___.",
  "Truth be told, if I had more money I would ___.",
  "Truth be told, I wish I had more time to ___.",
  "Truth be told, every day for lunch I could go to ___.",
  "Truth be told, I get pumped up when I hear ___.",
  "Truth be told, I feel old when ___.",
  "Truth be told, I spend too much time ___.",
  "Truth be told, I couldn't believe it when ___.",
  "Truth be told, I thought about becoming a ___.",
  "Truth be told, I get sentimental about ___.",
  "Truth be told, a big moment in my life was when ___.",
  "Truth be told, the TV game show that I would do well on is ___.",
  "Truth be told, I once wore pajamas with ___.",
  "Truth be told, I don't like dealing with ___.",
  "Truth be told, the problem I'm currently trying to figure out is ___.",
  "Truth be told, I once attended a class on ___.",
  "Truth be told, I have a lot of red ___.",
  "Truth be told, when I travel, I always make sure I take ___.",
  "Truth be told, I think they should outlaw ___.",
  "Truth be told, my favorite album or CD of all time is ___.",
  "Truth be told, a good thing about the town I live in is ___.",
  "Truth be told, I will never get rid of my ___.",
  "Truth be told, I hate going to ___.",
  "Truth be told, my best event in the Olympics would be ___.",
  "Truth be told, I'm as tough as ___.",
  "Truth be told, I procrastinate when it comes to ___.",
  "Truth be told, I would bend over backwards for ___.",
  "Truth be told, I once got angry with myself for ___.",
  "Truth be told, the weirdest gift I ever received was ___.",
  "Truth be told, the amusement park ride I like the most is ___.",
  "Truth be told, the best invention I've seen in my lifetime is ___.",
  "Truth be told, I once found ___.",
  "Truth be told, I don't like to be ___.",
  "Truth be told, I'm a nerd when it comes to ___.",
  "Truth be told, a technology I could not live without is ___.",
  "Truth be told, a great hiding spot is ___.",
  "Truth be told, I have a weakness for ___.",
  "Truth be told, I never leave home without ___.",
  "Truth be told, I have an old ___.",
  "Truth be told, the thing I fear most about growing old is ___.",
  "Truth be told, I used to have a crush on ___.",
  "Truth be told, I once collected ___.",
  "Truth be told, I need to ___.",
  "Truth be told, the best part of growing up is ___.",
  "Truth be told, I never understood the popularity of ___.",
  "Truth be told, my parents always warned me about ___.",
  "Truth be told, I think my theme song should be ___.",
  "Truth be told, I can actually sing all the words to ___.",
  "Truth be told, I don't like talking about ___.",
  "Truth be told, my mom made me wear ___.",
  "Truth be told, I have to admit I've never read ___.",
  "Truth be told, I get tired of talking about ___.",
  "Truth be told, the last thing I broke was ___.",
  "Truth be told, I think the title of my autobiography should be ___.",
  "Truth be told, I no longer eat ___.",
  "Truth be told, I have a phobia when it comes to ___.",
  "Truth be told, I think the most relaxing sound is ___.",
  "Truth be told, when driving I get aggravated by ___.",
  "Truth be told, most people consider me to be very ___.",
  "Truth be told, I wish I had never ___.",
  "Truth be told, the most annoying thing about traveling is ___.",
  "Truth be told, my family used to always go ___.",
  "Truth be told, a dumb thing I once did was ___.",
  "Truth be told, I think the best part about staying in a hotel is ___.",
  "Truth be told, if I could do it all over again, I would ___.",
  "Truth be told, the oldest thing I own is ___.",
  "Truth be told, I'm missing my ___.",
  "Truth be told, I often say to myself ___.",
  "Truth be told, something silly I believed as a kid was ___.",
  "Truth be told, I once had a nightmare about ___.",
  "Truth be told, I feel relaxed when I'm ___.",
  "Truth be told, the best thing about flying is ___.",
  "Truth be told, I gag when ___.",
  "Truth be told, the farthest I've traveled to was ___.",
  "Truth be told, the most drastic thing I've ever done to my hair is ___.",
  "Truth be told, I could see myself living in ___.",
  "Truth be told, the worst thing about being male is ___.",
  "Truth be told, about once a day I ___.",
  "Truth be told, one word that describes me is ___.",
  "Truth be told, I can't go a day without ___.",
  "Truth be told, when I stay at a hotel I ___.",
  "Truth be told, when I was younger I wanted to grow up to be a ___.",
  "Truth be told, the last thing I read was ___.",
  "Truth be told, I daydream about ___.",
  "Truth be told, I think my best feature is ___.",
  "Truth be told, I love going to ___.",
  "Truth be told, I think the worst form of exercise is ___.",
  "Truth be told, one time I laughed really hard when ___.",
  "Truth be told, I can't stand watching ___.",
  "Truth be told, what really grinds my gears is ___.",
  "Truth be told, I am a great ___.",
  "Truth be told, I never miss ___.",
  "Truth be told, one of my fondest memories is ___.",
  "Truth be told, I have a worn out ___.",
  "Truth be told, I'm thankful for ___.",
  "Truth be told, I need another ___.",
  "Truth be told, when someone says \"stretch pants\" I think of ___.",
  "Truth be told, my least favorite restaurant is ___.",
  "Truth be told, a memorable holiday experience was ___.",
  "Truth be told, a challenge I overcame was ___.",
  "Truth be told, I have a celebrity crush on ___.",
  "Truth be told, kids make me ___.",
  "Truth be told, I like to nibble on ___.",
  "Truth be told, I never thought I'd see the day when ___.",
  "Truth be told, the best thing to do on the playground is ___.",
  "Truth be told, on a rainy day, I like to ___.",
  "Truth be told, the ice cream flavor that best describes me is ___.",
  "Truth be told, I'm bored to tears with ___.",
  "Truth be told, the movie I wish my life were like is ___.",
  "Truth be told, I am so glad that I didn't ___.",
  "Truth be told, I have to admit that I've never seen ___.",
  "Truth be told, I love to eat ___.",
  "Truth be told, my new favorite thing is ___.",
  "Truth be told, I could never be a ___.",
  "Truth be told, a class I got a poor grade in was ___.",
  "Truth be told, it always surprises me when ___.",
  "Truth be told, I once dressed up as a ___.",
  "Truth be told, the person sitting to the right of me makes me feel ___.",
  "Truth be told, the weirdest thing I ever ate was ___.",
  "Truth be told, the worst place I've ever slept was ___.",
  "Truth be told, I am conservative when it comes to ___.",
  "Truth be told, I don't like to ___.",
  "Truth be told, I try to be good about ___.",
  "Truth be told, I come up with my best ideas when ___.",
  "Truth be told, I'll never understand ___.",
  "Truth be told, the idea that I wish I had come up with is ___.",
  "Truth be told, on Saturday mornings I look forward to ___.",
  "Truth be told, when I go to bed I wear ___.",
  "Truth be told, every day I expect ___.",
  "Truth be told, I could really use a break from ___.",
  "Truth be told, on my cell phone there's a picture of ___.",
  "Truth be told, don't get me started about ___.",
  "Truth be told, I grabbed the bull by the horns when ___.",
  "Truth be told, I can always fall back on my trusty ___.",
  "Truth be told, in my world, ___.",
  "Truth be told, sometimes I need a kick in the pants to ___.",
  "Truth be told, in the back of my refrigerator you would find ___.",
  "Truth be told, I like to snack on ___.",
  "Truth be told, I actually used to love ___.",
  "Truth be told, the first thing I think of when I wake up in the morning is ___.",
  "Truth be told, I think the best thing to open is ___.",
  "Truth be told, a good deed I once did was ___.",
  "Truth be told, I tend to be optimistic about ___.",
  "Truth be told, my family can never agree on ___.",
  "Truth be told, I wish I had never seen ___.",
  "Truth be told, I can't stand the taste of ___.",
  "Truth be told, something I once threw out and later regretted was ___.",
  "Truth be told, my first CD was ___.",
  "Truth be told, I consider it a great day when ___.",
  "Truth be told, it's been over a year since I ___.",
  "Truth be told, my favorite summer treat is ___.",
  "Truth be told, I once faked ___.",
  "Truth be told, the most annoying thing someone said to me recently was ___.",
  "Truth be told, I feel like a fish out of water when ___.",
  "Truth be told, a strange thing in my bedroom is ___.",
  "Truth be told, I always laugh at ___.",
  "Truth be told, I've never ___.",
  "Truth be told, the best present I ever got was ___.",
  "Truth be told, a smell that makes me gag is ___.",
  "Truth be told, one of my strongest memories of school lunch is ___.",
  "Truth be told, just once I wish I could ___.",
  "Truth be told, the most annoying thing about me is probably ___.",
  "Truth be told, I'm lucky because ___.",
  "Truth be told, I played a lot of ___.",
  "Truth be told, in a fire I would save ___.",
  "Truth be told, a good prank that someone played on me was ___.",
  "Truth be told, I take pride in ___.",
  "Truth be told, I can't stand listening to ___.",
  "Truth be told, people would be surprised to know that I once ___.",
  "Truth be told, during the winter I like to ___.",
  "Truth be told, I'm afraid of ___.",
  "Truth be told, a book I never finished reading is ___.",
  "Truth be told, the most dangerous thing I've done is ___.",
  "Truth be told, I believe you're never too old to ___.",
  "Truth be told, sometimes I listen to ___.",
  "Truth be told, I once fell asleep during ___.",
  "Truth be told, I have a habit of ___.",
  "Truth be told, I love the feeling of ___.",
  "Truth be told, I am a bad ___.",
  "Truth be told, my idea of the perfect morning is ___.",
  "Truth be told, I've always wanted to attend ___.",
  "Truth be told, the thing I search for most on the Internet is ___.",
  "Truth be told, the person that I'd least want to be stranded on a deserted island with is ___.",
  "Truth be told, I really need to ___.",
  "Truth be told, I cried when I saw ___.",
  "Truth be told, the first thing I see when I look in the mirror is ___.",
  "Truth be told, I think people are jealous of my ___.",
  "Truth be told, the nicest person I know is ___.",
  "Truth be told, I spend too much money on ___.",
  "Truth be told, I wouldn't have the patience to be a ___.",
  "Truth be told, the reality show I could win is ___.",
  "Truth be told, I never win at ___.",
  "Truth be told, I would like to be known for my ___.",
  "Truth be told, I know how to ___.",
  "Truth be told, I often gripe about ___.",
  "Truth be told, I don't like it when people say ___.",
  "Truth be told, I think the most overrated kitchen appliance is ___.",
  "Truth be told, I'm proud of ___.",
  "Truth be told, one of the best childhood games was ___.",
  "Truth be told, I used to be scared of ___.",
  "Truth be told, I think people see me as ___.",
  "Truth be told, I always say ___.",
  "Truth be told, the most embarrassing thing I ever bought was ___.",
  "Truth be told, for a billion dollars, I would ___.",
  "Truth be told, I hate the sound of ___.",
  "Truth be told, I have no problem spending money on ___.",
  "Truth be told, I don't believe ___.",
  "Truth be told, I once owned a lunchbox themed with ___.",
  "Truth be told, I wish I were ___.",
  "Truth be told, I think every party is better with ___.",
  "Truth be told, I couldn't live without ___.",
  "Truth be told, I would like to learn ___.",
  "Truth be told, a person who I think is overrated is ___.",
  "Truth be told, one thing that excites me is ___.",
  "Truth be told, all I need in life is ___.",
  "Truth be told, out of everyone here, I think I know the most about ___.",
  "Truth be told, I would love to see ___.",
  "Truth be told, it would be a thrill to meet ___.",
  "Truth be told, I'm trying to get better at ___.",
  "Truth be told, right now I could really go for a ___.",
  "Truth be told, I have an extra ___.",
  "Truth be told, a movie that makes me cry is ___.",
  "Truth be told, I live my life like I'm ___.",
  "Truth be told, I look best in ___.",
  "Truth be told, the last thing I bought at a drug store was ___.",
  "Truth be told, my best subject in school was ___.",
  "Truth be told, one time I lost ___.",
  "Truth be told, I would love to travel to ___.",
  "Truth be told, I would never ___.",
  "Truth be told, when I'm in the shower I think about ___.",
  "Truth be told, I cannot believe I own a ___.",
  "Truth be told, the stupidest thing I can recall doing is ___.",
  "Truth be told, the worst job I ever had was ___.",
  "Truth be told, I really miss ___.",
  "Truth be told, one time I was caught ___.",
  "Truth be told, the most famous person I have ever met is ___.",
  "Truth be told, I'm really particular when it comes to ___.",
  "Truth be told, I would never spend money on ___.",
  "Truth be told, an object I would \"un-invent\" is ___.",
  "Truth be told, I have accidentally ripped ___.",
  "Truth be told, I would love to ___.",
  "Truth be told, I can't stand it when people ___.",
  "Truth be told, in my home we never have enough ___.",
  "Truth be told, I think I am too young to ___.",
  "Truth be told, I once considered ___.",
  "Truth be told, the worst part about camping is ___.",
  "Truth be told, I feel young when ___.",
  "Truth be told, I would give up my day job to ___.",
  "Truth be told, when I was a kid I used to eat ___.",
  "Truth be told, I get a lot of ___.",
  "Truth be told, one time at a job interview I ___.",
  "Truth be told, I disapprove of ___.",
  "Truth be told, I love to shop at ___.",
  "Truth be told, the most expensive thing I purchased last month was ___.",
  "Truth be told, I recently read a book about ___.",
  "Truth be told, I think I would make a great ___.",
  "Truth be told, the last road trip I took was ___.",
  "Truth be told, I like to exercise my ___.",
  "Truth be told, I refuse to get ___.",
  "Truth be told, I guarantee that ___.",
  "Truth be told, my first crush was ___.",
  "Truth be told, I'm lucky because one time I ___.",
  "Truth be told, I will never trust ___.",
  "Truth be told, one time I got lost ___.",
  "Truth be told, my newest possession is ___.",
  "Truth be told, I have a secret ___.",
  "Truth be told, I wish I never grew up because ___.",
  "Truth be told, the worst part about weddings is ___.",
  "Truth be told, I once pretended to ___.",
  "Truth be told, I should go to a support group for ___.",
  "Truth be told, a book I liked as a child was ___.",
  "Truth be told, as I get older I am started to realize ___.",
  "Truth be told, I would never use another person's ___.",
  "Truth be told, I think I am too old to ___.",
  "Truth be told, I'm always ___.",
  "Truth be told, a phrase I want to learn in every language is ___.",
  "Truth be told, my parents would never let me ___.",
  "Truth be told, I would like to try ___.",
  "Truth be told, the most extreme thing I've done to impress someone I was interested in was ___.",
  "Truth be told, I wish I never learned ___.",
  "Truth be told, I wish I could take back the time I ___.",
  "Truth be told, tomorrow I plan on ___.",
  "Truth be told, I tend to exaggerate ___.",
  "Truth be told, I think people should pay a fine for ___.",
  "Truth be told, the best birthday gift I ever got was ___.",
  "Truth be told, I have a bad habit of ___.",
  "Truth be told, I wish I could be in the boxing ring with ___.",
  "Truth be told, I learned a lot from ___.",
  "Truth be told, I wish I could tame my ___.",
  "Truth be told, I'd really like a pair of ___.",
  "Truth be told, I actually like the movie ___.",
  "Truth be told, one moment I would relive is ___.",
  "Truth be told, I have a hard time ___.",
  "Truth be told, I get antsy when ___.",
  "Truth be told, I don't understand why you have to pay for ___.",
  "Truth be told, I will never go back to ___.",
  "Truth be told, a \"house rule\" in my home is ___.",
  "Truth be told, I once garbage picked ___.",
  "Truth be told, I could teach ___.",
  "Truth be told, the oldest article of clothing that I own is ___.",
  "Truth be told, my favorite article of clothing is ___.",
  "Truth be told, I once lived with someone who ___.",
  "Truth be told, the worst thing about being female is ___.",
  "Truth be told, I would wait in line 3 hours for ___.",
  "Truth be told, my friends think I'm ___.",
  "Truth be told, the strangest thing I saw at the mall was ___.",
  "Truth be told, the first movie I remember seeing in a theater is ___.",
  "Truth be told, I once sent away for ___.",
  "Truth be told, the most unusual thing I keep in my car is ___.",
  "Truth be told, there's a hole in my ___.",
  "Truth be told, I used to spend a lot of time ___.",
  "Truth be told, I once applied for a job as ___.",
  "Truth be told, you wouldn't believe that I once put ketchup on ___.",
  "Truth be told, I wish more people would ___.",
  "Truth be told, an important lesson I learned was ___.",
  "Truth be told, one time I wished for ___.",
  "Truth be told, the silliest thing I've done recently ___.",
  "Truth be told, when I'm stressed I ___.",
  "Truth be told, I was once in trouble for ___.",
  "Truth be told, I get stressed out when ___.",
  "Truth be told, something I would change about my physical appearance is ___.",
  "Truth be told, when I'm at the beach I like to ___.",
  "Truth be told, one time I hurt myself when I ___.",
  "Truth be told, I keep intending to ___.",
  "Truth be told, I love the smell of ___.",
  "Truth be told, my favorite word is ___.",
  "Truth be told, I once shook hands with ___.",
  "Truth be told, I overspent when I bought ___.",
  "Truth be told, one of my pet peeves is ___.",
  "Truth be told, the dumbest thing I ever bought was ___.",
  "Truth be told, at least once a week I ___.",
  "Truth be told, if you looked in my wallet right now you would find ___.",
  "Truth be told, my most recent impulse purchase was ___.",
  "Truth be told, my biggest pet peeve about work is ___.",
  "Truth be told, the funny thing about clowns is ___.",
  "Truth be told, to this day I still believe that ___.",
  "Truth be told, I still wear ___.",
  "Truth be told, a book I couldn't put down was ___.",
  "Truth be told, if I could change careers, I would be ___.",
  "Truth be told, I get annoyed by ___.",
  "Truth be told, I'm a fast ___.",
  "Truth be told, my dream car is ___.",
  "Truth be told, I have never ___.",
  "Truth be told, one thing that gives me the heebie-jeebies is ___.",
  "Truth be told, I never had the courage to ___.",
  "Truth be told, a show I always try to watch is ___.",
  "Truth be told, my lunch yesterday was ___.",
  "Truth be told, I should probably get more ___.",
  "Truth be told, I once met ___.",
  "Truth be told, I know diddly-squat about ___.",
  "Truth be told, the most amazing thing I have ever seen is ___.",
  "Truth be told, the best costume I've ever worn was ___.",
  "Truth be told, on a date I ___.",
  "Truth be told, I think the best song ever is ___.",
  "Truth be told, growing up I loved watching ___.",
  "Truth be told, I think the biggest waste of time is ___.",
  "Truth be told, when I need to get away from it all I ___.",
  "Truth be told, one time at a party I ___.",
  "Truth be told, the best thing I ever bought was ___.",
  "Truth be told, last week I should have ___.",
  "Truth be told, one of my guilty pleasures is ___.",
  "Truth be told, I once fixed a ___.",
  "Truth be told, I can ___.",
  "Truth be told, I used to really be into ___.",
  "Truth be told, I really just don't get why ___.",
  "Truth be told, when I can't sleep at night I ___.",
  "Truth be told, the best part of my childhood bedroom was ___.",
  "Truth be told, I feel like I'll never know how to ___.",
  "Truth be told, I used to think it was cool to ___.",
  "Truth be told, I am frequently ___.",
  "Truth be told, friends would say I have a small ___.",
  "Truth be told, my favorite reality show is ___.",
  "Truth be told, I enjoy the sound of ___.",
  "Truth be told, I would never watch a movie with ___.",
  "Truth be told, one time I was told I look like ___.",
  "Truth be told, I never learned how to ___.",
  "Truth be told, a food I wish were healthy is ___.",
  "Truth be told, the last movie I saw at the theater was ___.",
  "Truth be told, I never turn down a game of ___.",
  "Truth be told, I once had a conversation with the person next to me about ___.",
  "Truth be told, I often think, \"do we really need ___?\"",
  "Truth be told, I think I would get the award for \"The World's Best ___.\"",
];
