Cards = [
  "Truth be told, my favorite food-related mascot is ___.",
  "Truth be told, a great commercial is ___.",
  "Truth be told, I once made a ___.",
  "Truth be told, I've sworn off ___.",
  "Truth be told, I should clean up my ___.",
  "Truth be told, I once had my picture taken with ___.",
  "Truth be told, the last thing I fixed was ___.",
  "Truth be told, I keep meaning to ___.",
  "Truth be told, my first word should have been ___.",
  "Truth be told, I think I'm good at ___.",
  "Truth be told, I can't wait until computers can ___.",
  "Truth be told, the largest object that made me happy was ___.",
  "Truth be told, I always make sure I have enough ___.",
  "Truth be told, I often worry about ___.",
  "Truth be told, the weirdest thing I searched for on the internet was ___.",
  "Truth be told, I ___.",
  "Truth be told, I never forgot ___.",
  "Truth be told, I still have my ___.",
  "Truth be told, I have a pet name for ___.",
  "Truth be told, it's a little known fact that I ___.",
  "Truth be told, after a long day I really look forward to ___.",
  "Truth be told, I looooove to play ___.",
  "Truth be told, a game I was once addicted to playing was ___.",
  "Truth be told, the thing I own that I wish I didn't is ___.",
  "Truth be told, the next place I want to go is ___.",
  "Truth be told, I think a great thing about getting older is ___.",
  "Truth be told, the last time I broke a sweat, I was ___.",
  "Truth be told, I long for ___.",
  "Truth be told, I'm obsessive about ___.",
  "Truth be told, the animal or insect that terrifies me most is ___.",
  "Truth be told, one of my biggest accomplishments is ___.",
  "Truth be told, a big influence on me was ___.",
];
